In [3]:
import numpy as np

# PART 1: CREATING ARRAYS

## Creating an array and check its all attributes and methods

## creating arrays from python list, so list is the forge source here, later we use np.arrange() to create arrays directly so that with no list as forge source

In [2]:
lst_int = list(range(1, 6))

In [3]:
lst_int

[1, 2, 3, 4, 5]

In [5]:
lst_arr = np.array(lst_int)

In [6]:
lst_arr

array([1, 2, 3, 4, 5])

In [7]:
type(lst_arr)

numpy.ndarray

## ndim & shape & dtype method

### looks like numpy array attribute listed above has no "()" when calling

In [18]:
lst_arr.ndim()                           

TypeError: 'int' object is not callable

In [20]:
lst_arr.ndim                                         # ndim method

1

In [22]:
lst_arr.shape                                        # shape method               5 rows 1 column

(5,)

## Creating a matrix and check its all attributes and methods

In [2]:
lst_1 = [1, 2, 3]

In [3]:
lst_2 = [4, 5, 6]

In [5]:
lst_nest = [lst_1, lst_2]

In [6]:
lst_nest

[[1, 2, 3], [4, 5, 6]]

In [7]:
matrix = np.array(lst_nest)

In [8]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
mat_dim = matrix.ndim                                                   # ndim

In [10]:
mat_shape = matrix.shape                                                 # shape            2 rows 3 columns    

In [17]:
print(f"our created matrix is: \n {matrix}\n with dimension: {mat_dim} \n\tand\n shape: {mat_shape}")

our created matrix is: 
 [[1 2 3]
 [4 5 6]]
 with dimension: 2 
	and
 shape: (2, 3)


## .transpose() method                           , this method needs "()" when calling

In [19]:
mat_tran = matrix.transpose()

In [20]:
mat_tran

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
mat_tran.ndim

2

In [23]:
mat_tran.shape

(3, 2)

In [32]:
mat_tran[2, 0]

3

## np.arange() function

In [39]:
arr_even = np.arange(0, 11, 2)

In [40]:
arr_even

array([ 0,  2,  4,  6,  8, 10])

In [41]:
arr_odd = np.arange(1, 11, 2)

In [42]:
arr_odd

array([1, 3, 5, 7, 9])

In [43]:
arr_odd.ndim

1

In [44]:
arr_odd.shape

(5,)

In [45]:
arr_odd_tran = arr_odd.transpose()

In [48]:
print(arr_odd_tran)

[1 3 5 7 9]


In [46]:
arr_odd_tran.ndim

1

In [47]:
arr_odd_tran.shape

(5,)

In [49]:
arr_even_2 = np.arange(0, 11, 2, dtype = 'float32')

In [50]:
arr_even_2

array([ 0.,  2.,  4.,  6.,  8., 10.], dtype=float32)

In [53]:
arr_even_2.dtype                                 # .dtype method, with no "()" when calling like ndim & shape methods

dtype('float32')

## np.linspace()     function

In [54]:
arr_5_points = np.linspace(1, 5, 5)

In [55]:
arr_5_points

array([1., 2., 3., 4., 5.])

In [56]:
arr_5_points_2 = np.linspace(0, 5, 5)

In [57]:
arr_5_points_2

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [58]:
arr_default_50_intervals = np.linspace(51, 100)

In [59]:
arr_default_50_intervals

array([ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,  61.,
        62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
        73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,
        84.,  85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,
        95.,  96.,  97.,  98.,  99., 100.])

### changing Jupyter display

In [60]:
from IPython.core.interactiveshell import InteractiveShell

In [61]:
InteractiveShell.ast_node_interactivity = "all"

## zeros(), ones(), eye()

In [62]:
np.zeros(3)

array([0., 0., 0.])

In [64]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
np.ones(4)

array([1., 1., 1., 1.])

In [76]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
np.eye(1)

array([[1.]])

In [74]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [75]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## np.random module ->  rand(), randn(), randint()

In [77]:
np.random.rand(1)                                             # args for dimension

array([0.24709651])

In [78]:
np.random.rand(2)

array([0.91934145, 0.54261817])

In [80]:
np.random.rand(2,3)                                           # no inner "()" to enclose args

array([[0.62008036, 0.90000001, 0.35626891],
       [0.00514634, 0.41505792, 0.72208962]])

In [81]:
np.random.randn(1)                                           # args for dimension

array([0.18589516])

In [82]:
np.random.randn(2)

array([1.06011505, 0.27837157])

In [83]:
np.random.randn(2,3)

array([[-0.31957786, -0.04500779,  1.59858408],
       [-0.50143804, -1.33020075, -0.85437274]])

In [90]:
np.random.randint(1, 3)                                          # args for range, not dimension as rand() and randn()

2

In [91]:
np.random.randint(1, 100, 5)

array([78, 73, 86, 73, 82])

In [93]:
np.random.randint(1, 100, 5, dtype = 'int32')

array([89, 80, 30, 46, 28])

In [100]:
np.random.randint(1, 10, (2,3))

array([[9, 8, 1],
       [6, 7, 1]])

In [4]:
def roll_dice():
    """This func displays a value when a dice rolled"""
    dice_1 = np.random.randint(1,7)
    dice_2 = np.random.randint(1,7)
    if dice_1 == dice_2:
        msg = f"Bingo, it's a pair with num equals {dice_1}"
    else:
        if dice_1 < dice_2:
            msg = f"dice one is: {dice_1} less than dice two which is: {dice_2}"
        elif dice_1 > dice_2:
            msg = f"dice two is: {dice_2} less than dice one which is: {dice_1}"
    return msg

In [7]:
roll_dice()

'dice two is: 1 less than dice one which is: 3'

# PART 2: ARRAY MANIPULATION

## reshape(array, (size)) or array.reshape(size) 

In [114]:
freq = np.arange(10)

In [115]:
freq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
values = np.random.randn(10)

In [117]:
values

array([-1.1981894 ,  0.84062887, -0.34192223, -0.00700099, -0.47454366,
       -0.28010258, -0.27039848, -0.48873595,  1.62862296,  0.38005555])

In [122]:
freq.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [123]:
np.reshape(freq, (2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [124]:
np.reshape(values, (2,5))

array([[-1.1981894 ,  0.84062887, -0.34192223, -0.00700099, -0.47454366],
       [-0.28010258, -0.27039848, -0.48873595,  1.62862296,  0.38005555]])

In [125]:
values.reshape(2,5)

array([[-1.1981894 ,  0.84062887, -0.34192223, -0.00700099, -0.47454366],
       [-0.28010258, -0.27039848, -0.48873595,  1.62862296,  0.38005555]])

## .max()/        .min()/           .argmax()/           .argmin()

In [126]:
value_max = values.max()

In [127]:
value_max

1.6286229577715494

In [129]:
max(values)

1.6286229577715494

In [141]:
value_max_pos = values.argmax() + 1

In [142]:
value_max_pos

9

In [133]:
value_min = values.min()

In [134]:
value_min

-1.198189396862464

In [143]:
value_min_pos = values.argmin() + 1

In [144]:
value_min_pos

1

In [145]:
print(f"for values array, the maximun is {value_max} @ {value_max_pos},\n \t\t\tminimum is {value_min} @ {value_min_pos}")

for values array, the maximun is 1.6286229577715494 @ 9,
 			minimum is -1.198189396862464 @ 1


## array indexing and slicing

In [146]:
values

array([-1.1981894 ,  0.84062887, -0.34192223, -0.00700099, -0.47454366,
       -0.28010258, -0.27039848, -0.48873595,  1.62862296,  0.38005555])

In [147]:
values[0]

-1.198189396862464

In [148]:
values[-1]

0.38005555057340973

In [149]:
values[1:3]

array([ 0.84062887, -0.34192223])

### The main difference between arrays and lists is in the BROADCAST property of arrays.

In [44]:
lst_num = list(range(1, 11))

In [45]:
lst_num

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [46]:
lst_first_4 = lst_num[:4]

In [47]:
lst_first_4

[1, 2, 3, 4]

In [48]:
lst_first_4[:] = [111, 222, 333, 444]

In [49]:
lst_first_4

[111, 222, 333, 444]

In [50]:
lst_num

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### For arrays, however, a change in the slice of an array also updates or BROADCASTS to the original array, thereby changing its values.

In [8]:
arr_num = np.arange(1, 11)

In [9]:
arr_num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr_num_first_4 = arr_num[:4]

In [11]:
arr_num_first_4

array([1, 2, 3, 4])

In [12]:
arr_num_first_4 = [111, 222, 333, 444]                 # not using [:] makes it like in list case   

In [13]:
arr_num_first_4

[111, 222, 333, 444]

In [14]:
arr_num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### above experiment falis becoz of "arr_num_first_4 = [111, 222, 333, 444]"   

In [15]:
arr_num_first_4_sec = arr_num[:4]

In [16]:
arr_num_first_4_sec

array([1, 2, 3, 4])

In [17]:
arr_num_first_4_sec[:] = [111, 222, 333, 444]          # using [:] makes it right

In [18]:
arr_num_first_4_sec                  

array([111, 222, 333, 444])

In [19]:
arr_num                                                 # BROADCAST HAPPENS

array([111, 222, 333, 444,   5,   6,   7,   8,   9,  10])

## array.copy() method

In [20]:
arr_num = np.arange(1, 11)

In [21]:
arr_num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr_num_first_4_copy = arr_num.copy()[:4]

In [23]:
arr_num_first_4_copy

array([1, 2, 3, 4])

In [24]:
arr_num_first_4_copy[:] = 888

In [25]:
arr_num_first_4_copy

array([888, 888, 888, 888])

In [26]:
arr_num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr_num[:4]

array([1, 2, 3, 4])

## Grabbing elements from a matrix

In [95]:
matrix = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [96]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [97]:
matrix[1]

array([20, 25, 30])

In [98]:
matrix[2][0]

35

In [100]:
matrix[0:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [101]:
matrix[2, 2]

45

In [106]:
sec_column_slice = matrix[:, 1:2]

In [107]:
sec_column_slice

array([[10],
       [25],
       [40]])

In [110]:
sec_column_slice.ndim

2

In [111]:
sec_column_slice.shape

(3, 1)

In [108]:
sec_column_slice_2 = matrix[:, 1]

In [109]:
sec_column_slice_2

array([10, 25, 40])

In [112]:
sec_column_slice_2.ndim

1

In [113]:
sec_column_slice_2.shape

(3,)

In [28]:
large_arr = np.arange(0, 100, 2)

In [29]:
large_arr.shape

(50,)

In [30]:
large_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [31]:
large_mat = large_arr.reshape(5, 10)

In [124]:
large_mat

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [127]:
large_mat[3, 5]

70

In [128]:
large_mat[:3, :5]

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48]])

In [129]:
large_mat[:5, 8:9]

array([[16],
       [36],
       [56],
       [76],
       [96]])

In [130]:
large_mat[2:4, 7:9]

array([[54, 56],
       [74, 76]])

## Conditional selection

Consider a case where we need to extract certain values from an array that meet a Boolean criterion. NumPy offers a convenient way of doing this without having to use loops.

In [133]:
lst_odd = list(range(1, 20, 2))

In [134]:
lst_odd

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [135]:
criterion = lambda i : i > 10

In [137]:
lst_odd_greater_10 = filter(criterion, lst_odd)

In [139]:
list(lst_odd_greater_10)

[11, 13, 15, 17, 19]

In [140]:
arr_odd = np.arange(1, 20, 2)

In [141]:
arr_odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [142]:
arr_bool = arr_odd > 10

In [144]:
arr_bool

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [145]:
arr_odd[arr_bool]

array([11, 13, 15, 17, 19])

In [148]:
arr_odd[arr_odd > 15]                         # compact expression and it is recommended

array([17, 19])

In [149]:
large_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [150]:
large_arr[large_arr > 80][:10].reshape(3,3)

array([[82, 84, 86],
       [88, 90, 92],
       [94, 96, 98]])

## NumPy Array Operations

In [152]:
arr_1 = np.arange(1, 11).reshape(2,5)

In [153]:
arr_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [154]:
arr_2 = np.random.randn(10).reshape(2,5)

In [155]:
arr_2

array([[-0.19163499, -0.24385382, -1.16742829, -1.4498936 , -0.08036857],
       [ 0.5274855 ,  2.04819257, -1.56992629,  2.08780519, -1.48874071]])

In [156]:
arr_sum = arr_1 + arr_2

In [157]:
arr_sum

array([[ 0.80836501,  1.75614618,  1.83257171,  2.5501064 ,  4.91963143],
       [ 6.5274855 ,  9.04819257,  6.43007371, 11.08780519,  8.51125929]])

In [158]:
arr_sub = arr_1 - arr_2

In [159]:
arr_sub

array([[ 1.19163499,  2.24385382,  4.16742829,  5.4498936 ,  5.08036857],
       [ 5.4725145 ,  4.95180743,  9.56992629,  6.91219481, 11.48874071]])

In [160]:
arr_multi = arr_1 * arr_2                                # this is element-wise product

In [161]:
arr_multi                 

array([[ -0.19163499,  -0.48770765,  -3.50228487,  -5.79957438,
         -0.40184286],
       [  3.16491298,  14.33734798, -12.5594103 ,  18.79024667,
        -14.88740712]])

In [162]:
arr_div = arr_1 / arr_2                                   # this is element-wise division

In [163]:
arr_div

array([[ -5.2182538 ,  -8.20163476,  -2.56975098,  -2.75882314,
        -62.21337392],
       [ 11.37472034,   3.4176474 ,  -5.09578065,   4.31074703,
         -6.71708641]])

In [184]:
arr_0_10 = np.arange(0, 10)

In [185]:
arr_0_10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [186]:
scalar = 100

In [187]:
arr_100_109 = arr_1_10 + scalar

In [188]:
arr_100_109

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [189]:
arr_0_10_revert = arr_100_109 - 100

In [190]:
arr_0_10_revert

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [191]:
arr_0_10_revert * scalar

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [192]:
arr_0_10_revert / scalar

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [194]:
arr_0_10_revert / arr_0_10_revert                         # nan generated in numpy array operation without stopping the program

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

## Universal Array functions (U-Func), I think they're not methods

In [195]:
arr_0_10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [196]:
scalar

100

In [197]:
u_add = np.add(arr_0_10, scalar)

In [198]:
u_add

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [199]:
u_sub = np.subtract(arr_0_10, scalar)

In [200]:
u_sub

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91])

In [202]:
u_log = np.log(arr_0_10[1:])

In [203]:
u_log

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [204]:
u_sin = np.sin(arr_0_10)

In [205]:
u_sin

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [206]:
u_divide = np.divide(arr_0_10, scalar)

In [207]:
u_divide

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [210]:
arr_0_10.sin()                                      # methods not working cuz it's a function   

AttributeError: 'numpy.ndarray' object has no attribute 'sin'

In [211]:
arr_0_10.max()

9

In [212]:
np.max(arr_0_10)

9

In [213]:
arr_0_10.argmin()

0

In [214]:
np.argmin(arr_0_10)

0